---
- name: Install Vim and configure plugins
  hosts: localhost
  become: yes

  tasks:
    - name: Install Vim and Git
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - vim
        - git

    - name: Create .vim/autoload directory
      file:
        path: "~/.vim/autoload"
        state: directory

    - name: Download vim-plug
      get_url:
        url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
        dest: "~/.vim/autoload/plug.vim"

    - name: Create .vim/plugged directory
      file:
        path: "~/.vim/plugged"
        state: directory

    - name: Copy .vimrc configuration file
      copy:
        src: "files/.vimrc"
        dest: "~/.vimrc"
        owner: "poiipoii"
        group: "poiipoii"
        mode: 0644

    - name: Install Vim plugins using vim-plug
      shell: "vim +PlugInstall +qall"


